### ISSUE TITLE
使用方法

### ISSUE THREAD

**Issue by kulalasmile** [surmrf/xproxy-chrome#1]
请问改插件如何安装，是否支持www.aaa.com/api  -----> www.bbb.com/xx这种规则

**Comment by surmrf** [comment]
问题1：自己修改代码后安装？
答：可以参考 chrome 开发中插件安装

问题2：是否支持 www.aaa.com/api -----> www.bbb.com/xx这种规则？
答：chrome 插件不能进行非静态资源的代理，因为原来是通过 307 重定向实现
